"""One-shot script: restructure feeds.xml from 33 source-type folders to 14 topic folders."""

import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path

FEEDS_XML = Path(__file__).resolve().parent.parent / "feeds.xml"

NEW_FOLDERS = [
    "Alerts & Advisories",
    "News & Media",
    "Exploitation & Vuln Research",
    "Malware & Threat Intel",
    "Reverse Engineering",
    "Offensive Security",
    "Cloud & Supply Chain",
    "Hardware, Embedded & ICS",
    "Cryptography & Privacy",
    "Forensics & Incident Response",
    "Application Security",
    "Research & Papers",
    "Newsletters & Digests",
    "General & Mixed",
]

# Maps xmlUrl substring → new folder.
# Matched in order; first match wins.
URL_MAP: list[tuple[str, str]] = [
    # ── Alerts & Advisories ────────────────────────────────────────────────
    ("packetstormsecurity.org",                         "Alerts & Advisories"),
    ("usn.ubuntu.com",                                  "Alerts & Advisories"),
    ("seclists.org/rss/fulldisclosure",                 "Alerts & Advisories"),
    ("zerodayinitiative.com/rss/upcoming",              "Alerts & Advisories"),
    ("kirbyidau.com",                                   "Alerts & Advisories"),
    ("exploitalert.com",                                "Alerts & Advisories"),
    ("fortiguard/rss/ir",                               "Alerts & Advisories"),
    ("cve.threatint.com",                               "Alerts & Advisories"),
    ("linuxsecurity.com/advisories",                    "Alerts & Advisories"),
    ("digital.nhs.uk/feed/cyber-alerts",               "Alerts & Advisories"),
    ("medium.com/feed/@cve_program",                    "Alerts & Advisories"),
    ("cert.at",                                         "Alerts & Advisories"),
    ("cert.be",                                         "Alerts & Advisories"),
    ("cyber.gc.ca",                                     "Alerts & Advisories"),
    ("kyberturvallisuuskeskus.fi",                      "Alerts & Advisories"),
    ("hkcert.org",                                      "Alerts & Advisories"),
    ("jpcert.or.jp",                                    "Alerts & Advisories"),
    ("blogs.jpcert.or.jp",                              "Alerts & Advisories"),
    ("cert.lv",                                         "Alerts & Advisories"),
    ("cert.si",                                         "Alerts & Advisories"),
    ("ncsc.gov.uk",                                     "Alerts & Advisories"),
    ("cisa.gov",                                        "Alerts & Advisories"),
    ("cert.pl",                                         "Alerts & Advisories"),
    ("ria.ee",                                          "Alerts & Advisories"),
    ("cisecurity.org/feed/advisories",                  "Alerts & Advisories"),
    ("isc.sans.edu",                                    "Alerts & Advisories"),
    ("isac.bio",                                        "Alerts & Advisories"),
    ("first.org/newsroom",                              "Alerts & Advisories"),
    ("duo.com/decipher",                                "News & Media"),
    ("duo.com/feed",                                    "Alerts & Advisories"),
    ("aws.amazon.com/security/security-bulletins",      "Alerts & Advisories"),
    ("feeds.feedburner.com/HaveIBeenPwned",             "Alerts & Advisories"),
    ("kernel.org/feeds/kdist",                          "Alerts & Advisories"),

    # ── Research & Papers ──────────────────────────────────────────────────
    ("ieeexplore.ieee.org",                             "Research & Papers"),
    ("dl.acm.org",                                      "Research & Papers"),
    ("rss.acm.org",                                     "Research & Papers"),
    ("arxiv.org/rss/cs.CR",                             "Research & Papers"),
    ("export.arxiv.org/rss/cs.CR",                      "Research & Papers"),
    ("csdl-api.computer.org",                           "Research & Papers"),
    ("iacr.org/news/rss",                               "Research & Papers"),

    # ── Newsletters & Digests ──────────────────────────────────────────────
    ("bluepurple.substack.com",                         "Newsletters & Digests"),
    ("lastweekinaws.com",                               "Newsletters & Digests"),
    ("campaign-archive.com",                            "Newsletters & Digests"),
    ("newsletter.blockthreat.io",                       "Newsletters & Digests"),
    ("danielengberg.com/category/newsletter",           "Newsletters & Digests"),
    ("apisecurity.io",                                  "Newsletters & Digests"),
    ("thisweekin4n6.com",                               "Newsletters & Digests"),
    ("cloudseclist.com",                                "Newsletters & Digests"),
    ("badcyber.com",                                    "Newsletters & Digests"),
    ("riskybiznews.substack.com",                       "Newsletters & Digests"),
    ("tldrsec.com",                                     "Newsletters & Digests"),
    ("blog.badsectorlabs.com",                          "Newsletters & Digests"),
    ("it4sec.substack.com",                             "Newsletters & Digests"),
    ("osintnewsletter.com",                             "Newsletters & Digests"),
    ("catless.ncl.ac.uk/risksrss",                      "Newsletters & Digests"),
    ("talkback.sh/resources/feed",                      "Newsletters & Digests"),
    ("opalsec.substack.com",                            "Newsletters & Digests"),
    ("risky.biz/feeds/risky-business",                  "Newsletters & Digests"),
    ("risky.biz/feeds/risky-business-news",             "Newsletters & Digests"),
    ("rss.beehiiv.com/feeds/tLSvUYOBwf",               "Newsletters & Digests"),

    # ── Cryptography & Privacy ─────────────────────────────────────────────
    ("signal.org/blog",                                 "Cryptography & Privacy"),
    ("blog.cryptographyengineering.com",                "Cryptography & Privacy"),
    ("imperialviolet.org",                              "Cryptography & Privacy"),
    ("lightbluetouchpaper.org",                         "Cryptography & Privacy"),
    ("citizenlab.ca",                                   "Cryptography & Privacy"),
    ("spreadprivacy.com",                               "Cryptography & Privacy"),
    ("protonmail.com/blog",                             "Cryptography & Privacy"),
    ("protonvpn.com/blog",                              "Cryptography & Privacy"),
    ("proton.me/blog",                                  "Cryptography & Privacy"),
    ("privateinternetaccess.com/blog",                  "Cryptography & Privacy"),
    ("restoreprivacy.com",                              "Cryptography & Privacy"),
    ("sciencedaily.com/rss/computers_math/encryption",  "Cryptography & Privacy"),
    ("globalencryption.org",                            "Cryptography & Privacy"),
    ("reddit.com/r/privacy",                            "Cryptography & Privacy"),
    ("abetterinternet.org",                             "Cryptography & Privacy"),
    ("act.eff.org",                                     "Cryptography & Privacy"),
    ("eff.org/rss/updates",                             "Cryptography & Privacy"),
    ("letsencrypt.org",                                 "Cryptography & Privacy"),
    ("electrospaces.net",                               "Cryptography & Privacy"),
    ("scotthelme.co.uk",                                "Cryptography & Privacy"),
    ("biometricupdate.com",                             "Cryptography & Privacy"),
    ("feedburner.com/biometricupdate",                  "Cryptography & Privacy"),
    ("helpmewithhipaa.com",                             "Cryptography & Privacy"),
    ("inteltechniques.com",                             "Cryptography & Privacy"),
    ("bof.nl",                                          "Cryptography & Privacy"),

    # ── Hardware, Embedded & ICS ───────────────────────────────────────────
    ("firmwaresecurity.com",                            "Hardware, Embedded & ICS"),
    ("iot-tests.org",                                   "Hardware, Embedded & ICS"),
    ("ics-cert.kaspersky.com",                          "Hardware, Embedded & ICS"),
    ("cert-portal.siemens.com",                         "Hardware, Embedded & ICS"),
    ("ceres-c.it",                                      "Hardware, Embedded & ICS"),
    ("hackaday.com",                                    "Hardware, Embedded & ICS"),
    ("home-assistant.io",                               "Hardware, Embedded & ICS"),
    ("blog.arduino.cc",                                 "Hardware, Embedded & ICS"),
    ("iotinsights.com",                                 "Hardware, Embedded & ICS"),
    ("rtl-sdr.com",                                     "Hardware, Embedded & ICS"),
    ("scadamag.infracritical.com",                      "Hardware, Embedded & ICS"),
    ("industrialcyber.co",                              "Hardware, Embedded & ICS"),
    ("axis.com/blog/secure-insights",                   "Hardware, Embedded & ICS"),

    # ── Reverse Engineering ────────────────────────────────────────────────
    ("binary.ninja",                                    "Reverse Engineering"),
    ("reverse.put.as",                                  "Reverse Engineering"),
    ("msreverseengineering.com",                        "Reverse Engineering"),
    ("doar-e.github.io",                                "Reverse Engineering"),
    ("n10info.blogspot.com",                            "Reverse Engineering"),
    ("openrce.org",                                     "Reverse Engineering"),
    ("reddit.com/r/ReverseEngineering",                 "Reverse Engineering"),
    ("jtsylve.blog",                                    "Reverse Engineering"),

    # ── Forensics & Incident Response ─────────────────────────────────────
    ("reddit.com/r/computerforensics",                  "Forensics & Incident Response"),
    ("aboutdfir.com",                                   "Forensics & Incident Response"),
    ("forensicfocus.com",                               "Forensics & Incident Response"),
    ("thedfirreport.com",                               "Forensics & Incident Response"),
    ("blog.didierstevens.com",                          "Forensics & Incident Response"),
    ("cadosecurity.com",                                "Forensics & Incident Response"),
    ("reddit.com/r/blueteamsec",                        "Forensics & Incident Response"),
    ("jacknaglieri.substack.com",                       "Forensics & Incident Response"),
    ("dalchecco.it",                                    "Forensics & Incident Response"),
    ("ericconrad.com",                                  "Forensics & Incident Response"),
    ("taosecurity.blogspot.com",                        "Forensics & Incident Response"),

    # ── Malware & Threat Intel ─────────────────────────────────────────────
    ("github.com/mandiant/capa",                        "Malware & Threat Intel"),
    ("reddit.com/r/Malware",                            "Malware & Threat Intel"),
    ("malware.news",                                    "Malware & Threat Intel"),
    ("hshrzd.wordpress.com",                            "Malware & Threat Intel"),
    ("blog.chainalysis.com",                            "Malware & Threat Intel"),
    ("clearskysec.com",                                 "Malware & Threat Intel"),
    ("feedburner.com/Abusech",                          "Malware & Threat Intel"),
    ("feedburner.com/HOTforSecurity",                   "Malware & Threat Intel"),
    ("cyble.com",                                       "Malware & Threat Intel"),
    ("sentinelone.com",                                 "Malware & Threat Intel"),
    ("welivesecurity.com",                              "Malware & Threat Intel"),
    ("research.checkpoint.com",                         "Malware & Threat Intel"),
    ("sophos.com",                                      "Malware & Threat Intel"),
    ("blog.netlab.360.com",                             "Malware & Threat Intel"),
    ("blog.google/threat-analysis-group",               "Malware & Threat Intel"),
    ("secureworks.com/rss?feed=research",               "Malware & Threat Intel"),
    ("secureworks.com/rss?feed=blog",                   "Malware & Threat Intel"),
    ("decoded.avast.io",                                "Malware & Threat Intel"),
    ("nortonlifelock.com",                              "Malware & Threat Intel"),
    ("securelist.com",                                  "Malware & Threat Intel"),
    ("feedburner.com/feedburner/Talos",                 "Malware & Threat Intel"),
    ("feeds.feedburner.com/feedburner/Talos",           "Malware & Threat Intel"),
    ("nviso.eu",                                        "Malware & Threat Intel"),
    ("securityintelligence.com",                        "Malware & Threat Intel"),
    ("socradar.io",                                     "Malware & Threat Intel"),
    ("blog.reversinglabs.com",                          "Malware & Threat Intel"),
    ("cloudblog.withgoogle.com/topics/threat-intelligence", "Malware & Threat Intel"),
    ("blog.malwarebytes.org",                           "Malware & Threat Intel"),
    ("unit42.paloaltonetworks.com",                     "Malware & Threat Intel"),
    ("flashpoint.io",                                   "Malware & Threat Intel"),
    ("flare.io",                                        "Malware & Threat Intel"),
    ("huntress.com",                                    "Malware & Threat Intel"),
    ("feedburner.com/Clamav",                           "Malware & Threat Intel"),
    ("johannesbader.ch",                                "Malware & Threat Intel"),
    ("malwaretech.com",                                 "Malware & Threat Intel"),
    ("asec.ahnlab.com",                                 "Malware & Threat Intel"),
    ("anomali.com",                                     "Malware & Threat Intel"),
    ("fox-it.com",                                      "Malware & Threat Intel"),
    ("darknetlive.com",                                 "Malware & Threat Intel"),
    ("redcanary.com",                                   "Malware & Threat Intel"),
    ("resecurity.com",                                  "Malware & Threat Intel"),
    ("crowdstrike.com",                                 "Malware & Threat Intel"),
    ("blog.virustotal.com",                             "Malware & Threat Intel"),
    ("trendmicro.com",                                  "Malware & Threat Intel"),
    ("feeds.trendmicro.com",                            "Malware & Threat Intel"),
    ("symantec",                                        "Malware & Threat Intel"),
    ("sed-cms.broadcom.com",                            "Malware & Threat Intel"),
    ("microsoft.com/security/blog",                     "Malware & Threat Intel"),
    ("proofpoint.com",                                  "Malware & Threat Intel"),
    ("deepinstinct.com",                                "Malware & Threat Intel"),
    ("contagiodump.blogspot.com",                       "Malware & Threat Intel"),

    # ── Exploitation & Vuln Research ──────────────────────────────────────
    ("googleprojectzero.blogspot.com",                  "Exploitation & Vuln Research"),
    ("immunityservices.blogspot.com",                   "Exploitation & Vuln Research"),
    ("rhinosecuritylabs.com",                           "Exploitation & Vuln Research"),
    ("feeds.feedburner.com/positiveTechnologies",       "Exploitation & Vuln Research"),
    ("blog.zecops.com",                                 "Exploitation & Vuln Research"),
    ("swarm.ptsecurity.com",                            "Exploitation & Vuln Research"),
    ("medium.com/feed/tenable-techblog",                "Exploitation & Vuln Research"),
    ("research.nccgroup.com",                           "Exploitation & Vuln Research"),
    ("blog.trailofbits.com",                            "Exploitation & Vuln Research"),
    ("objective-see.com",                               "Exploitation & Vuln Research"),
    ("spiderlabs",                                      "Exploitation & Vuln Research"),
    ("trustwave.com",                                   "Exploitation & Vuln Research"),
    ("labs.taszk.io",                                   "Exploitation & Vuln Research"),
    ("blog.calif.io",                                   "Exploitation & Vuln Research"),
    ("vusec.net",                                       "Exploitation & Vuln Research"),
    ("reddit.com/r/blackhat",                           "Exploitation & Vuln Research"),
    ("reddit.com/r/fulldisclosure",                     "Exploitation & Vuln Research"),
    ("blog.quarkslab.com",                              "Exploitation & Vuln Research"),
    ("labs.watchtowr.com",                              "Exploitation & Vuln Research"),
    ("nullcathedral.com",                               "Exploitation & Vuln Research"),
    ("samcurry.net",                                    "Exploitation & Vuln Research"),
    ("cylab.be",                                        "Exploitation & Vuln Research"),
    ("thezdi.com",                                      "Exploitation & Vuln Research"),
    ("qualys.com",                                      "Exploitation & Vuln Research"),
    ("feeds.feedburner.com/tenable",                    "Exploitation & Vuln Research"),
    ("tenable.com/feed",                                "Exploitation & Vuln Research"),
    ("rapid7.com",                                      "Exploitation & Vuln Research"),
    ("positive.security",                               "Exploitation & Vuln Research"),
    ("rcesecurity.com",                                 "Exploitation & Vuln Research"),
    ("greynoise.io",                                    "Exploitation & Vuln Research"),
    ("sploitus.com",                                    "Exploitation & Vuln Research"),
    ("exploit-db.com",                                  "Exploitation & Vuln Research"),
    ("dayzerosec.com",                                  "Exploitation & Vuln Research"),
    ("vulncheck.com",                                   "Exploitation & Vuln Research"),
    ("xploitlab.com",                                   "Exploitation & Vuln Research"),
    ("criminalip.io",                                   "Exploitation & Vuln Research"),

    # ── Offensive Security ─────────────────────────────────────────────────
    ("grugq.tumblr.com",                                "Offensive Security"),
    ("medium.com/feed/@thegrugq",                       "Offensive Security"),
    ("carnal0wnage.blogspot.com",                       "Offensive Security"),
    ("diablohorn.com",                                  "Offensive Security"),
    ("blog.compass-security.com",                       "Offensive Security"),
    ("reddit.com/r/redteamsec",                         "Offensive Security"),
    ("johnjhacking.com",                                "Offensive Security"),
    ("bishopfox.com",                                   "Offensive Security"),
    ("kali.org",                                        "Offensive Security"),
    ("feedburner.com/PentestTools",                     "Offensive Security"),
    ("blackhillsinfosec.com",                           "Offensive Security"),
    ("trustedsec.com",                                  "Offensive Security"),
    ("synack.com",                                      "Offensive Security"),
    ("praetorian.com",                                  "Offensive Security"),

    # ── Cloud & Supply Chain ───────────────────────────────────────────────
    ("feedburner.com/akamai",                           "Cloud & Supply Chain"),
    ("wiz.io",                                          "Cloud & Supply Chain"),
    ("blog.aquasec.com",                                "Cloud & Supply Chain"),
    ("blogs.juniper.net",                               "Cloud & Supply Chain"),
    ("aws.amazon.com/blogs/security/tag/aws-threat-research-team", "Cloud & Supply Chain"),
    ("aws.amazon.com/blogs/security",                   "Cloud & Supply Chain"),
    ("securitylabs.datadoghq.com",                      "Cloud & Supply Chain"),
    ("netskope.com",                                    "Cloud & Supply Chain"),
    ("hackingthe.cloud",                                "Cloud & Supply Chain"),
    ("cloudsecurityalliance.org",                       "Cloud & Supply Chain"),
    ("hacking-the.cloud",                               "Cloud & Supply Chain"),
    ("elastic.co/blog",                                 "Cloud & Supply Chain"),
    ("legitsecurity.com",                               "Cloud & Supply Chain"),
    ("latio.tech",                                      "Cloud & Supply Chain"),
    ("redhat.com/en/rss/blog/channel/security",        "Cloud & Supply Chain"),
    ("blog.cloudflare.com",                             "Cloud & Supply Chain"),
    ("umbrella.cisco.com",                              "Cloud & Supply Chain"),
    ("medium.com/feed/@chroniclesec",                   "Cloud & Supply Chain"),
    ("forescout.com",                                   "Cloud & Supply Chain"),
    ("cloudvulndb.org",                                 "Cloud & Supply Chain"),
    ("blog.sonatype.com",                               "Cloud & Supply Chain"),
    ("medium.com/feed/netflix-techblog/tagged/security", "Cloud & Supply Chain"),
    ("thenewstack.io",                                  "Cloud & Supply Chain"),
    ("labs.ripe.net",                                   "Cloud & Supply Chain"),
    ("github.blog",                                     "Cloud & Supply Chain"),

    # ── Application Security ───────────────────────────────────────────────
    ("portswigger.net/daily-swig",                      "Application Security"),
    ("blog.mozilla.org/security",                       "Application Security"),
    ("security.googleblog.com",                         "Application Security"),
    ("f5.com/labs",                                     "Application Security"),
    ("blog.doyensec.com",                               "Application Security"),
    ("veracode.com",                                    "Application Security"),
    ("sucuri.net",                                      "Application Security"),
    ("wordfence.com",                                   "Application Security"),
    ("owasp.blogspot.com",                              "Application Security"),
    ("embracethered.com",                               "Application Security"),
    ("fingerprint.com",                                 "Application Security"),
    ("palant.info",                                     "Application Security"),
    ("daniel.haxx.se",                                  "Application Security"),
    ("medium.com/feed/@guardiosecurity",                "Application Security"),
    ("imperva.com/blog",                                "Application Security"),
    ("blog.pcisecuritystandards.org",                   "Application Security"),
    ("wesecureapp.com",                                 "Application Security"),
    ("absoluteappsec.com",                              "Application Security"),
    ("reddit.com/r/websec",                             "Application Security"),
    ("blog.securityinnovation.com",                     "Application Security"),
    ("pentestpartners.com",                             "Application Security"),

    # ── News & Media ───────────────────────────────────────────────────────
    # (catch-all for broad news/media — must come after all topic rules)
    ("therecord.media",                                 "News & Media"),
    ("wired.com/feed/category/security",                "News & Media"),
    ("bleepingcomputer.com",                            "News & Media"),
    ("krebsonsecurity.com",                             "News & Media"),
    ("schneier.com",                                    "News & Media"),
    ("grahamcluley.com",                                "News & Media"),
    ("feedburner.com/TheHackersNews",                   "News & Media"),
    ("securityweek.com",                                "News & Media"),
    ("darkreading.com",                                 "News & Media"),
    ("theregister.co.uk/security",                      "News & Media"),
    ("zdnet.com",                                       "News & Media"),
    ("arstechnica.com",                                 "News & Media"),
    ("techrepublic.com",                                "News & Media"),
    ("hackread.com",                                    "News & Media"),
    ("techxplore.com",                                  "News & Media"),
    ("scworld.com",                                     "News & Media"),
    ("dysruptionhub.com",                               "News & Media"),
    ("news.crunchbase.com",                             "News & Media"),
    ("cybersecurityventures.com",                       "News & Media"),
    ("cybersecuritydive.com",                           "News & Media"),
    ("cshub.com",                                       "News & Media"),
    ("cybersecuritynews.com",                           "News & Media"),
    ("sciencedaily.com/rss/computers_math/hacking",     "News & Media"),
    ("feedburner.com/HealthTechMagazine",               "News & Media"),
    ("infosecurity-magazine.com",                       "News & Media"),
    ("news.mit.edu/topic/mitcyber",                     "News & Media"),
    ("newscientist.com",                                "News & Media"),
    ("itnews.com.au",                                   "News & Media"),
    ("itnews.asia",                                     "News & Media"),
    ("rekt.news",                                       "News & Media"),
    ("ghacks.net",                                      "News & Media"),
    ("securityaffairs.com",                             "News & Media"),
    ("csoonline.com",                                   "News & Media"),
    ("reddit.com/r/cybersecurity",                      "News & Media"),
    ("cshub.com/rss/articles",                          "News & Media"),
    ("theguardian.com/technology/data-computer-security","News & Media"),
    ("tech.eu/category/cybersecurity",                  "News & Media"),
    ("bankinfosecurity.com",                            "News & Media"),
    ("digitaljournal.com",                              "News & Media"),
    ("gbhackers.com",                                   "News & Media"),
    ("feedburner.com/gbhackers",                        "News & Media"),
    ("heimdalsecurity.com",                             "News & Media"),
    ("esecurityplanet.com",                             "News & Media"),
    ("govinfosecurity.com",                             "News & Media"),
    ("infosecwriteups.com",                             "News & Media"),
    ("itpro.com",                                       "News & Media"),
    ("datacenterdynamics.com",                          "News & Media"),
    ("helpnetsecurity.com",                             "News & Media"),
    ("restofworld.org",                                 "News & Media"),
    ("techtarget.com/searchsecurity",                   "News & Media"),
    ("securityboulevard.com",                           "News & Media"),
    ("venturebeat.com/category/security",               "News & Media"),
    ("siliconangle.com/category/security",              "News & Media"),
    ("security-incidents.de",                           "News & Media"),
    ("medium.com/feed/netflix-techblog",                "News & Media"),
    ("medium.com/feed/@netflixtechblog",               "News & Media"),
    ("techspot.com",                                    "News & Media"),
    ("theinformation.com",                              "News & Media"),
    ("techmonitor.ai",                                  "News & Media"),
    ("lastwatchdog.com",                                "News & Media"),
    ("troyhunt.com",                                    "News & Media"),
    ("feedburner.com/TroyHunt",                         "News & Media"),
    ("siliconrepublic.com",                             "News & Media"),
    ("cybersecuritypulse.net",                          "News & Media"),
    ("securityledger.com",                              "News & Media"),
    ("threatpost.com",                                  "News & Media"),
    ("smashingsecurity.com",                            "News & Media"),
    ("malicious.life",                                  "News & Media"),
    ("computerweekly.com",                              "News & Media"),
    ("hackmageddon.com",                                "News & Media"),
    ("reddit.com/r/netsec",                             "News & Media"),
    ("reddit.com/r/pwned",                              "News & Media"),
    ("reddit.com/r/Information_Security",               "News & Media"),
    ("reddit.com/r/InfoSecNews",                        "News & Media"),
    ("reddit.com/r/ComputerSecurity",                   "News & Media"),
    ("europol.europa.eu",                               "News & Media"),
    ("facecrooks.com",                                  "News & Media"),
    ("databreachtoday.co.uk",                           "News & Media"),
    ("ddosecrets.substack.com",                         "News & Media"),
    ("bellingcat.com",                                  "News & Media"),
    ("44con.com",                                       "News & Media"),
    ("techmeme.com",                                    "News & Media"),
    ("news.ycombinator.com",                            "News & Media"),
    ("theverge.com",                                    "News & Media"),
    ("feeds.a.dj.com/rss/RSSWSJD",                     "News & Media"),
    ("9to5mac.com",                                     "News & Media"),
    ("washingtonpost.com/rss/business/technology",      "News & Media"),
    ("feeds.bloomberg.com/technology",                  "News & Media"),
    ("interestingengineering.com",                      "News & Media"),
    ("techcrunch.com",                                  "News & Media"),
    ("loopinsight.com",                                 "News & Media"),
    ("feeds2.feedburner.com/thenextweb",                "News & Media"),
    ("feeds.mashable.com",                              "News & Media"),
    ("forbes.com/innovation",                           "News & Media"),
    ("rss.nytimes.com/services/xml/rss/nyt/Technology", "News & Media"),
    ("betanews.com",                                    "News & Media"),
    ("boingboing.net",                                  "News & Media"),
    ("ciodive.com",                                     "News & Media"),
    ("cyberscoop.com",                                  "News & Media"),
    ("engadget.com",                                    "News & Media"),
    ("fastcompany.com/technology",                      "News & Media"),
    ("feeds.arstechnica.com",                           "News & Media"),
    ("gizmodo.com",                                     "News & Media"),
    ("macrumors.com",                                   "News & Media"),
    ("technologyreview.com",                            "News & Media"),
    ("osxdaily.com",                                    "News & Media"),
    ("rss.slashdot.org",                                "News & Media"),
    ("feedburner.com/typepad/alleyinsider",             "News & Media"),
    ("wired.com/feed/rss",                              "News & Media"),
    ("wired.com/feed/category",                         "News & Media"),
    ("blog.ubuntu.com",                                 "News & Media"),
    ("apple.com/newsroom",                              "News & Media"),
    ("blog.google/rss",                                 "News & Media"),
    ("engineering.fb.com",                              "News & Media"),
    ("netflixinvestor.com",                             "News & Media"),
    ("techblog.netflix.com",                            "News & Media"),
    ("propublica.org",                                  "News & Media"),
    ("icij.org",                                        "News & Media"),
    ("theintercept.com",                                "News & Media"),
    ("reddit.com/r/science",                            "News & Media"),
    ("feedburner.com/businessinsider/science",          "News & Media"),
    ("cisco.com",                                       "News & Media"),
    ("microsoft.com",                                   "News & Media"),
    ("blogs.microsoft.com",                             "News & Media"),
    ("netblocks.org",                                   "News & Media"),
    ("protos.com",                                      "News & Media"),
    ("404media.co",                                     "News & Media"),
    ("c4isrnet.com",                                    "News & Media"),
    ("producthunt.com",                                 "News & Media"),
    ("gbhackers.com",                                   "News & Media"),
    ("itsecurityguru.org",                              "News & Media"),
    ("infosecuritybuzz.com",                            "News & Media"),
    ("feedburner.com/InformationSecurityBuzz",          "News & Media"),
    ("ventureinsecurity.net",                           "News & Media"),
]

# Name-based fallback patterns (applied when URL matching fails)
NAME_MAP: list[tuple[str, str]] = [
    ("CERT",            "Alerts & Advisories"),
    ("Advisory",        "Alerts & Advisories"),
    ("Alert",           "Alerts & Advisories"),
    ("Malware",         "Malware & Threat Intel"),
    ("Threat",          "Malware & Threat Intel"),
    ("Ransomware",      "Malware & Threat Intel"),
    ("Forensic",        "Forensics & Incident Response"),
    ("DFIR",            "Forensics & Incident Response"),
    ("Reverse Eng",     "Reverse Engineering"),
    ("Cloud",           "Cloud & Supply Chain"),
    ("Privacy",         "Cryptography & Privacy"),
    ("Crypto",          "Cryptography & Privacy"),
    ("AppSec",          "Application Security"),
    ("Hardware",        "Hardware, Embedded & ICS"),
    ("ICS",             "Hardware, Embedded & ICS"),
    ("Newsletter",      "Newsletters & Digests"),
    ("Digest",          "Newsletters & Digests"),
    ("Paper",           "Research & Papers"),
    ("IEEE",            "Research & Papers"),
    ("arXiv",           "Research & Papers"),
]


def assign_folder(name: str, url: str) -> str:
    for pattern, folder in URL_MAP:
        if pattern in url:
            return folder
    for pattern, folder in NAME_MAP:
        if pattern.lower() in name.lower():
            return folder
    return "General & Mixed"


def restructure(path: Path) -> None:
    tree = ET.parse(path)
    root = tree.getroot()
    body = root.find("body")

    # Collect all feeds, deduplicate by xmlUrl
    seen_urls: set[str] = set()
    buckets: dict[str, list[ET.Element]] = defaultdict(list)

    for folder in body:
        for feed in folder:
            url = feed.get("xmlUrl", "")
            if not url or url in seen_urls:
                continue
            seen_urls.add(url)
            name = feed.get("text", "")
            target = assign_folder(name, url)
            buckets[target].append(feed)

    # Rebuild body with new folders in canonical order
    for child in list(body):
        body.remove(child)

    total = 0
    for folder_name in NEW_FOLDERS:
        feeds = buckets.get(folder_name, [])
        feeds.sort(key=lambda f: f.get("text", "").lower())
        folder_el = ET.SubElement(body, "outline", text=folder_name, title=folder_name)
        for feed in feeds:
            folder_el.append(feed)
        total += len(feeds)
        print(f"  {len(feeds):4d}  {folder_name}")

    # Anything that didn't match goes to General & Mixed (already handled above)
    print(f"\n  {total} feeds across {len(NEW_FOLDERS)} folders")
    print(f"  {len(seen_urls) - total} duplicates removed")

    ET.indent(root, space="  ")
    xml_str = ET.tostring(root, encoding="unicode")
    path.write_text(f"<?xml version='1.0' encoding='UTF-8'?>\n{xml_str}\n", encoding="utf-8")
    print(f"\nWrote {path}")


if __name__ == "__main__":
    restructure(FEEDS_XML)
